### ISSUE TITLE
Google sign-In Branding not compliant

### ISSUE THREAD

**Issue by ghost** [lipis/bootstrap-social#177]
Hi , I just received this email from Google after submitting the app for verification. 
Are you planning any update ?

Dear Developer,
--
Thank you for submitting a verification request.   To proceed with the approval process, please ensure that your   project --------- is in compliance with the   following requirements.   Google Sign-In Branding   The Google sign-in button on your project's homepage   URL is not compliant with the Google sign-in branding guidelines. Please   update the Google sign-in button on your website according to Google   sign-in branding guidelines.   Thank you for your patience. Please reply back to this email   after your project is in compliance with the requirements above.

**Comment by alb-xss** [comment]
Red color (related to Google+) must be dropped according the new branding guidelines.
Here more information: https://developers.google.com/identity/branding-guidelines

**Comment by TimothyBramlett** [comment]
Is there a plan to make the Google Sign-In Compliant?

**Comment by holtkamp** [comment]
@TimothyBramlett this might be a workaround to overrule this library settings:

```css
.btn-social.btn-google {
    background-color: #FFFFFF;
    color: #1F1F1F;
    font-family: Roboto, Arial, sans-serif;
}

.btn-social.btn-google > :first-child {
    color: transparent;
    background-image: url('https://fonts.gstatic.com/s/i/productlogos/googleg/v6/24px.svg');
    background-position: center;
    background-repeat: no-repeat;
}
```

![Screenshot 2023-11-29 at 12 36 51](https://github.com/lipis/bootstrap-social/assets/776405/7ef9223f-7516-4da8-9b0c-cc316a2d71d2)
